export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG='en_US.UTF-8'

typeset -gU cdpath fpath mailpath path

path=(
    /usr/local/{bin,sbin}
    $path
)

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
