# Many thanks to:
# https://github.com/myfreeweb/dotfiles

DOT="${HOME}/dotfiles"

### plugins ####################################################################

source "${DOT}/zsh/zgen/zgen.zsh"
if ! zgen saved; then
    echo ">> Generating zgen configuration"
    # prezto options
    zgen prezto editor key-bindings 'emacs'
    zgen prezto editor dot-expansion 'yes'
    zgen prezto '*' color 'yes'
    zgen prezto '*' case-sensitive 'yes'
    #zgen prezto prompt theme 'sorin'
    zgen prezto prompt theme 'steeef'

    # prezto and modules
    zgen prezto
    zgen prezto environment
    zgen prezto terminal
    zgen prezto editor
    zgen prezto git
    zgen prezto history
    zgen prezto directory
    zgen prezto spectrum
    zgen prezto utility
    zgen prezto completion

    zgen prezto syntax-highlighting
    zgen prezto prompt

    # plugins
    zgen save
    echo ">> Done"
fi

### color scheme ###############################################################

base16_scheme() {
	local SCHEME="${DOT}/zsh/base16-shell/scripts/base16-$*.sh"
    if [ -e $SCHEME ]; then
	    source  $SCHEME
    else
        echo "$ERROR Can't find color scheme '$SCHEME'"
    fi
}

day() { base16_scheme "atelier-seaside-light" }
night() { base16_scheme "atelier-seaside" }

#night

[[ -e $commands[vim]  ]] && export EDITOR=vim  VISUAL=vim
[[ -e $commands[nvim] ]] && export EDITOR=nvim VISUAL=nvim
alias vi=$VISUAL

export LESS='-g -i -q -R -S -w -z-4'
export TERM=xterm-256color
export DEFAULT_USER="vladimir"

if [[ -d ${HOME}/.jenv ]]; then
eval "$(jenv init -)"
fi

unsetopt correct

################################################################################

export JAVA7_HOME=$(/usr/libexec/java_home -v 1.7)
export JAVA8_HOME=$(/usr/libexec/java_home -v 1.8)
export JAVA9_HOME=$(/usr/libexec/java_home -v 9)
export JAVA10_HOME=$(/usr/libexec/java_home -v 10)

################################################################################

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

parse_git_dirty() {
  [[ $(git status 2> /dev/null | tail -n1) != "nothing to commit (working directory clean)" ]] && echo "●"
}
parse_git_branch() {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/[\1$(parse_git_dirty)]/"
}

iterm2_print_user_vars() {
  iterm2_set_user_var dirName "$(print -P "%$(( $COLUMNS ))<...<%~%<<")"
  iterm2_set_user_var dirInfo "$(print -P "%$(( $COLUMNS ))<...<%~%<<") $(parse_git_branch)"
}

test -e "${DOT}/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh" && source ${DOT}/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
