export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'

JAVA_HOME8=$(/usr/libexec/java_home -v 1.8)
JAVA_HOME=${JAVA_HOME8}

export JAVA_HOME8 JAVA_HOME
